version: '3.2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  web:
    build: .
    container_name: briga-web
    ports:
      - 4000:4000
    depends_on:
      - db
    env_file:
      - .env